### ISSUE TITLE
Question about B/C

### ISSUE THREAD

**Issue by infograf768** [algo26-matthias/idna-convert#14]
We use idna convert for Joomla.
Is this library B/C with the former mso one?

**Comment by glensc** [comment]
@infograf768 you should have created two way backlink, i.e link to the origin issue as well: https://github.com/joomla/joomla-cms/pull/24009

however, if packagist picks up changes from this repository to old packagist name, then there's semver compatibility issue, and next version in the new repo should be 2.x, not 1.x cc @algo26-matthias 

- https://packagist.org/packages/mso/idna-convert
- https://packagist.org/packages/algo26-matthias/idna-convert

otherwise the compatibility should be fine:
- https://github.com/joomla/joomla-cms/pull/24009#issuecomment-467364577

**Comment by glensc** [comment]
i think if the token is different (or removed) then the `mso/idna-convert` should not get any more updates.

- https://packagist.org/packages/mso/idna-convert#dev-master - 2017-08-20 18:52 UTC
 - c1c253b797f1091bc469e5d297ed4fdd25afd59f
- https://packagist.org/packages/algo26-matthias/idna-convert#dev-master - 2019-02-25 07:49 UTC
 - 07dc5a61d86ffdd1af476f869d10e24cb5632efa

so, as the master branches are different, the old packagist package does not seem to get updates.

**Comment by glensc** [comment]
cc @algo26-matthias

**Comment by algo26-matthias** [comment]
@glensc Thanks for mentioning me. To end confusion about the package I tagged the latest commit as being v2.0.1. HTH!
